### ISSUE TITLE
Admit Null fields in Embed and WebObject

### ISSUE THREAD

**Issue by javis86** [ToshiroZ/Discord-Webhook#1]
Definitions on Discord Developer Portal shows the use of nulls in several fieds (https://discord.com/developers/docs/resources/channel#embed-object)
![image](https://user-images.githubusercontent.com/5216084/113705944-73710b00-96b4-11eb-8443-b73eff221721.png)

Is It possible to add it?
I'm trying to send an embed without title
I'm using the package in https://github.com/javis86/Serilog.Sinks.Discord.Lite
Thanks

**Comment by ToshiroZ** [comment]
I can work on adding the ability to pass in null but why would you need to pass in a null value. And while messing with discord bots a null title when sending embeds made the embed not send so I'm not sure if it's valid

**Comment by javis86** [comment]
Could you upload the latest changes to the repo (1.0.7)? I'm trying to add videos and images and i havent do it with 1.0.4

**Comment by ToshiroZ** [comment]
Sorry did not know you made a reply. What is the issue you are having as I haven't put work into this issue. And what do you mean upload most recent changes. I push to github repo then make a nuget update.

**Comment by javis86** [comment]
Hi Tozhiro! I've been comparing the code of WebhookObject in Github and the same class in Nuget 
[fuget version of file](https://www.fuget.org/packages/Discord.Webhook/1.0.7/lib/netstandard2.0/Discord%20Webhook.dll/Discord.Webhook/WebhoohObject) which depends on nuget package and there are changes on ToString() method. 

Github:
![image](https://user-images.githubusercontent.com/5216084/115145723-61368b80-a029-11eb-91be-31e5a572c0ab.png)

Nuget package class:
![image](https://user-images.githubusercontent.com/5216084/115145683-31878380-a029-11eb-8623-52b6fca52611.png)

**Comment by ToshiroZ** [comment]
> Hi Tozhiro! I've been comparing the code of WebhookObject in Github and the same class in Nuget
> [fuget version of file](https://www.fuget.org/packages/Discord.Webhook/1.0.7/lib/netstandard2.0/Discord%20Webhook.dll/Discord.Webhook/WebhoohObject) which depends on nuget package and there are changes on ToString() method.
> 
> Github:
> ![image](https://user-images.githubusercontent.com/5216084/115145723-61368b80-a029-11eb-91be-31e5a572c0ab.png)
> 
> Nuget package class:
> ![image](https://user-images.githubusercontent.com/5216084/115145683-31878380-a029-11eb-8623-52b6fca52611.png)

There are no real differences in the tostring function. That's caused by the compiler. The two pieces of code are functionally identical.
