### ISSUE TITLE
Strong name signature not valid for this assembly Discord Webhook.dll

### ISSUE THREAD

**Issue by XQaij79DLCo3K1lYowiX** [ToshiroZ/Discord-Webhook#12]
when i publish and run setup.exe in a project with version 1.0.9 of the package it errors on install. when i use 1.0.8 version it works fine. i have clickonce manifest signed and assembly signed, despite this the issue persists.
![image](https://github.com/ToshiroZ/Discord-Webhook/assets/133459899/164e089c-9c1e-4b6c-bfda-749db0d1af48)
if it is of use, this is the part of the logs where the error occurred:

Strong name signature not valid for this assembly Discord Webhook.dll.
		- Source: System.Deployment
		- Stack trace:

from what i can gather this error is not the fault of my own, but i could be wrong
if you need any more information please let me know

**Comment by celldra** [comment]
We’ve removed strong name signing in the latest staged version. Apologies for the delay in responding; this library is maintained periodically.
